# Generated by Django 3.2.18 on 2023-05-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_conversion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="full_shorten_url",
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="full_url",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="url_shorten_key",
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
