# Generated by Django 3.2.18 on 2023-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_conversion", "0002_auto_20230518_1008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="full_url",
            field=models.URLField(null=True, unique=True),
        ),
    ]
